In [5]:
from google.colab import drive
drive.mount('/content/drive')

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
import pandas as pd

data=pd.read_csv('/content/drive/MyDrive/ML_lab_data/Employee_Salary.csv')
data.head(10)
data.info()
data.describe()
data.isnull().sum()

data['Age']=data['Age'].fillna(data['Age'].mean())
data['Salary']=data['Salary'].fillna(data['Salary'].mean())

data.isnull().sum()

le_Gender=LabelEncoder()
data['Gender_encoded']=le_Gender.fit_transform(data['Gender'])

data.head()

scaler=MinMaxScaler()
data['Age_scaled']=scaler.fit_transform(data[['Age']])
data['Salary_scaled']=scaler.fit_transform(data[['Salary']])

data.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                35 non-null     int64
 1   Experience_Years  35 non-null     int64
 2   Age               35 non-null     int64
 3   Gender            35 non-null     object
 4   Salary            35 non-null     int64
dtypes: int64(4), object(1)
memory usage: 1.5+ KB

,ID,Experience_Years,Age,Gender,Salary,Gender_encoded,Age_scaled,Salary_scaled
0,1,5,28,Female,250000,0,0.244444,0.024707
1,2,1,21,Male,50000,1,0.088889,0.004701
2,3,3,23,Female,170000,0,0.133333,0.016705
3,4,2,22,Male,25000,1,0.111111,0.002201
4,5,1,17,Male,10000,1,0.000000,0.000700